### ISSUE TITLE
test data on EtherCIS - need ability to clean out & repopulate 

### ISSUE THREAD

**Issue by tony-shannon** [ethercis/ethercis#108]
Hi @chevalleyc and @freshehr
Can I get a view on steps we need to take on to be able to clear out existing test data & be able to repopulate with a clean set of decent test data for 5-10 test patients for 5-10 core headings?
Need to be able to this regularly and on ad hoc basis.
thanks for views on how to achieve this
Tony

**Comment by freshehr** [comment]
Hin - not a major issue - We can do this fairly easily with Postman. Marand now has a hard delete EHR api call which it would be good to replicate in Ethercis i.e completely remove all compositions and the ehr object itself for a given patient. 

Re-loading data is easy - just needs a little more work on creating a few more realistic test data instances but we can probably resource that ok.

**Comment by tony-shannon** [comment]
thanks @freshehr 
Could you outline the steps we need to take when you get a chance please..
Are you happy to oversee & sort?

**Comment by tony-shannon** [comment]
Please keep this open until @freshehr  confirms this is done
My understand is that he is working on this this week , thanks

**Comment by freshehr** [comment]
@tony-shannon - We are pretty well there now.

All of the headings that can be populated from the CDR appear to be working other than

Events - longstanding issue - currently All events for all patients are being displayed.

Orders - Ethercis -stored data is not being displayed correctly in PulseTile. Very odd as the data is being saved ok and retreived correctly/identically to Marand CDR data. VCan we ask Rob Tweed to investigate QEWD aspects as everyhing seems ok from my Pov and we know the UI works with Marand.

Lab Tests - Tests are being populated and displayed correctly but not the analyte results. This is a known issue with EtherCis AQL escaping objects incorrectly.

I would prefer to get the Orders issue clarified before populating a completely clean patient record. Currently http://dev.ripple.foundation/#/patients/9999999015 has the best set on Ethercis but some duplicates because of testing.

**Comment by tony-shannon** [comment]
thanks for update @freshehr 

@robtweed could you update Ian and this thread on your recent work which can help with test data population/deletion as far as I understand it?

**Comment by chevalleyc** [comment]
I think a lot of these issues are potentially fixed. Otherwise please feel free to open new CR with ONE issue per ticket. Thank you.
