### ISSUE TITLE
generating jooq sources is done by a windows batch file

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#17]
This makes making changes to the database schema and regenerating the jooq sources more work.
Why not removing the generated sources from the repository and have the jooq sources generated as needed by a plugin for the build system. ?

(our fork used the gradle plugin to do that)

**Comment by ethercis** [comment]
The issue is that jOOQ uses a deployed DB to build the corresponding compiled binding. This is why it's manual at this time since we don't have a reference versioned DB somewhere that we can use for code generation. Perhaps we should further investigate to either access a reference DB in the Cloud or rebuild the DB locally for build purpose based on the latest DDL. WDYT?

**Comment by ralphvanetten** [comment]
I think using a solution like flyway you can make sure the DB schema is up to date before running jooq. In our fork I just did that, before running the jooq generator, flyway gets a change to make sure the database schema is up to date.

**Comment by chevalleyc** [comment]
See [PR#5](https://github.com/ethercis/ehrservice/pull/5/commits)
