### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by raphaeloneves** [ethercis/ethercis#2]
Hi, guys. I'm following all the instructions to deploy the app, but i'm having problems with JMX. Can you help me, please? Here is my stacktrace:
```
Listening for transport dt_socket at address: 8000
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Property: File 'services.properties' not found
Property: could not find default property file, will try from command line arguments
Property: No args array given.
Property: Loading /etc/opt/ecis/services.properties from directory /home/ethercis
Property: Added 3 property pairs
11:06:05.165 [main] ERROR com.ethercis.servicemanager.jmx.JmxWrapper - JMX registration problem for 'com.ethercis:nodeClass=node,node="logg
ing"': javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:336)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:319)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:693)
        at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:673)
        at com.ethercis.servicemanager.jmx.JmxWrapper.<init>(JmxWrapper.java:177)
        at com.ethercis.servicemanager.jmx.JmxWrapper.getInstance(JmxWrapper.java:123)
        at com.ethercis.servicemanager.cluster.RunTimeSingleton.getJmxWrapper(RunTimeSingleton.java:255)
        at com.ethercis.servicemanager.cluster.RunTimeSingleton.registerMBean(RunTimeSingleton.java:304)
        at com.ethercis.servicemanager.runlevel.RunlevelManager.initJmx(RunlevelManager.java:123)
        at com.ethercis.servicemanager.cluster.RunTimeSingleton.getRunlevelManager(RunTimeSingleton.java:1614)
        at com.ethercis.vehr.VEhrGateServlet.init(VEhrGateServlet.java:233)
        at com.ethercis.vehr.Launcher.start(Launcher.java:108)
        at com.ethercis.vehr.Launcher.startServer(Launcher.java:77)
        at com.ethercis.vehr.Launcher.main(Launcher.java:194)
Caused by: java.lang.NullPointerException
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:333)
        ... 14 more
11:06:10.078 [main] ERROR com.ethercis.servicemanager.cluster.ClusterInfo - Unable to load service identified as:SessionLoggerService,1.0. 
Please check your code...
```
I added the session-logger-service into my classpath, but no results. Removed all the jmx references in ther ecis-server script too, but the problem still there.

Hope you can help me!
Regards.

Raphael

**Comment by ethercis** [comment]
Hi Raphael
  
 Hmmm... I thought I retired the session logger :( I have attached a script of a currently running instance in UK (you could also check the updated script in the Operon docker instance). Anyway, just make sure the session logger (session-logger-service-1.0-SNAPSHOT) is not in your classpath. It was intended to provide connected clients with a way to get the list of active users. Mainly oriented to support 1-to-1 chat between users.
 
 I'm off during this Easter break, but please let me know how it goes.
  
 Thanks -- Christian
  
  
  

----------------------------------------

**Comment by maxcda101** [comment]
Hi Raphael, Christian
Have you solved the problem yet? i have been problem too. Here is my stacktrace, when i start ecis-server.
`Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Listening for transport dt_socket at address: 8000
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Property: File 'services.properties' not found
Property: could not find default property file, will try from command line arguments
Property: No args array given.
Property: Loading /etc/opt/ecis/services.properties from directory /
Property: Added 3 property pairs
07:16:12.126 [main] ERROR com.ethercis.servicemanager.jmx.JmxWrapper - JMX registration problem for 'com.ethercis:nodeClass=node,node="logging"': javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:336)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:319)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:693)
	at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:673)
	at com.ethercis.servicemanager.jmx.JmxWrapper.<init>(JmxWrapper.java:177)
	at com.ethercis.servicemanager.jmx.JmxWrapper.getInstance(JmxWrapper.java:123)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.getJmxWrapper(RunTimeSingleton.java:255)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.registerMBean(RunTimeSingleton.java:304)
	at com.ethercis.servicemanager.runlevel.RunlevelManager.initJmx(RunlevelManager.java:123)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.getRunlevelManager(RunTimeSingleton.java:1614)
	at com.ethercis.vehr.VEhrGateServlet.init(VEhrGateServlet.java:233)
	at com.ethercis.vehr.Launcher.start(Launcher.java:108)
	at com.ethercis.vehr.Launcher.startServer(Launcher.java:77)
	at com.ethercis.vehr.Launcher.main(Launcher.java:194)
Caused by: java.lang.NullPointerException
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:333)
	... 14 more
log4j:WARN Continuable parsing error 3 and column 15
log4j:WARN Document root element "Configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 3 and column 15
log4j:WARN Document is invalid: no grammar found.
log4j:ERROR DOM element is - not a <log4j:configuration> element.
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
Property: Added 0 property pairs
`
Hope you can help me!
Thanks.

**Comment by ethercis** [comment]
Hi Quan, could you post your ecis-server script please? Will try to reproduce this issue locally. Btw did you remove SessionLogger from your classpath? Thanks

**Comment by maxcda101** [comment]
@ethercis Here is my ecis-server script, i added "session-logger-service-1.0-SNAPSHOT.jar" into CLASSPATH.
```
#!/bin/bash
# description: Controls Ethercis Server
# processname: ecis-server
#
# SCRIPT created 15-10-2015, CCH
# Rev 1.1. September 2016. Uses v1.1.0 SNAPSHOT
#-----------------------------------------------------------------------------------
UNAME=`uname`
HOSTNAME=`hostname`
export ECIS_DEPLOY_BASE=/opt/ecis
export SYSLIB=${ECIS_DEPLOY_BASE}/lib/system
export COMMONLIB=${ECIS_DEPLOY_BASE}/lib/common
export APPLIB=${ECIS_DEPLOY_BASE}/lib/application
export LIB=${ECIS_DEPLOY_BASE}/lib/deploy

# Mailer configuration
ECIS_MAILER=echo

# use the right jvm library depending on the OS
# NB: EtherCIS requires java 8
if [ :${UNAME}: = :Linux: ];
then
  JAVA_HOME=/opt/java/jdk1.8.0_102/jre
fi
if [ :${UNAME}: = :SunOS: ];
then
  JAVA_HOME=/jdk1.8.0_102/jre
fi

#force to use IPv4 so Jetty can bind to it instead of IPv6...
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

# runtime parameters
export JVM=${JAVA_HOME}/bin/java
export RUNTIME_HOME=/opt/ecis
export RUNTIME_ETC=/etc/opt/ecis
export RUNTIME_LOG=/var/opt/ecis
export RUNTIME_DIALECT=EHRSCAPE  #specifies the query dialect used in HTTP requests (REST)
export SERVER_PORT=8080 # the port address to bind to
export SERVER_HOST=127.0.0.1 # the network address to bind to

export MAILER_CONF=${RUNTIME_ETC}/xcmail.cf

export JOOQ_DIALECT=POSTGRES
JOOQ_DB_PORT=5432
JOOQ_DB_HOST=localhost
JOOQ_DB_SCHEMA=ethercis
export JOOQ_URL=jdbc:postgresql://${JOOQ_DB_HOST}:${JOOQ_DB_PORT}/${JOOQ_DB_SCHEMA}
export JOOQ_DB_LOGIN=postgres
export JOOQ_DB_PASSWORD=posgres

CLASSPATH=./:\
${JAVA_HOME}/lib:\
${LIB}/ecis-core-1.1.1-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-cache-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehrdao-1.1.0-SNAPSHOT.jar:\
${LIB}/jooq-pg-1.1.0-SNAPSHOT.jar:\
${LIB}/aql-processor-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-validation-1.0-SNAPSHOT.jar:\
${LIB}/ecis-transform-1.0-SNAPSHOT.jar:\
${LIB}/ecis-servicemanager-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-authenticate-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-logon-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-resource-access-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-composition-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-partyidentified-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-system-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-vehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-query-service-1.0.0-SNAPSHOT.jar:\
${APPLIB}/ehrxml.jar:\
${APPLIB}/oet-parser.jar:\
${APPLIB}/ecis-openehr.jar:\
${APPLIB}/types.jar:\
${APPLIB}/adl-parser-1.0.9.jar:\
${APPLIB}/session-logger-service-1.0-SNAPSHOT.jar
# launch server
# ecis server is run as user ethercis
su - ethercis << _ECIS
case "$1" in
  start)
    echo "ethercis startup"
     ( ${ECIS_MAILER} ${MAILER_CONF} "EtherCIS Startup" "Manual invocation of server startup" > /dev/null )&
    (
	${JVM} \
	-Xmx256M \
	-Xms256M \
	-server \
	-XX:-EliminateLocks \
	-XX:-UseVMInterruptibleIO \
	-cp ${CLASSPATH} \
	-Xdebug \
	-Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y \
	-Djava.util.logging.config.file=${RUNTIME_ETC}/logging.properties \
	-Dlog4j.configuration=file:${RUNTIME_ETC}/log4j.xml \
	-Djava.net.preferIPv4Stack=true \
	-Djava.awt.headless=true \
	-Djdbc.drivers=org.postgresql.Driver \
    	-Dserver.node.name=vm01.ethercis.org \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=8999 \
    	-Dcom.sun.management.jmxremote.local.only=false \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
    	-Dfile.encoding=UTF-8 \
    	-Djava.rmi.server.hostname=${SERVER_HOST} \
	-Djooq.dialect=${JOOQ_DIALECT} \
	-Djooq.url=${JOOQ_URL} \
	-Djooq.login=${JOOQ_DB_LOGIN} \
	-Djooq.password=${JOOQ_DB_PASSWORD} \
	-Druntime.etc=${RUNTIME_ETC} \
	 com.ethercis.vehr.Launcher \
	-propertyFile /etc/opt/ecis/services.properties \
    	-server_host 127.0.0.1 \
    	-server_port 8080 \
 2>> ${RUNTIME_LOG}/ethercis_test.log >> ${RUNTIME_LOG}/ethercis_test.log &    )&
    ;;
  stop)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Stop" "Manual invocation of server STOP" > /dev/null )&
    echo "ethercis shutdown"
    pkill java
    ;;
  restart)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Restart" "Manual invocation of server RESTART" )&
    echo "ethercis restarting"
    $0 stop
    $0 start
    ;;
  clean)
    (${ECIS_MAILER} ${MAILER_CONF} "Ethercis CLEAR" "Manual invocation of server Clear logs" > dev/null )&
    echo "ethercis clear"
    $0 stop
	rm -rf {RUNTIME_LOG}/ethercis_test.log
    ;;
  *)
    echo "Usage: ecis-server {start|stop|restart|clean}"
    exit 1
esac
_ECIS
exit 0
# end of file
```

**Comment by ethercis** [comment]
Could you remove '${APPLIB}/session-logger-service-1.0-SNAPSHOT.jar' from CLASSPATH and try to run the server?

**Comment by maxcda101** [comment]
I removed it, here is new my stacktrace
```
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Listening for transport dt_socket at address: 8000
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Property: File 'services.properties' not found
Property: could not find default property file, will try from command line arguments
Property: No args array given.
Property: Loading /etc/opt/ecis/services.properties from directory /
Property: Added 3 property pairs
09:03:12.528 [main] ERROR com.ethercis.servicemanager.jmx.JmxWrapper - JMX registration problem for 'com.ethercis:nodeClass=node,node="logging"': javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
javax.management.NotCompliantMBeanException: Bad getMBeanInfo()
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:336)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:319)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:693)
	at com.ethercis.servicemanager.jmx.JmxWrapper.registerMBean(JmxWrapper.java:673)
	at com.ethercis.servicemanager.jmx.JmxWrapper.<init>(JmxWrapper.java:177)
	at com.ethercis.servicemanager.jmx.JmxWrapper.getInstance(JmxWrapper.java:123)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.getJmxWrapper(RunTimeSingleton.java:255)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.registerMBean(RunTimeSingleton.java:304)
	at com.ethercis.servicemanager.runlevel.RunlevelManager.initJmx(RunlevelManager.java:123)
	at com.ethercis.servicemanager.cluster.RunTimeSingleton.getRunlevelManager(RunTimeSingleton.java:1614)
	at com.ethercis.vehr.VEhrGateServlet.init(VEhrGateServlet.java:233)
	at com.ethercis.vehr.Launcher.start(Launcher.java:108)
	at com.ethercis.vehr.Launcher.startServer(Launcher.java:77)
	at com.ethercis.vehr.Launcher.main(Launcher.java:194)
Caused by: java.lang.NullPointerException
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getNewMBeanClassName(DefaultMBeanServerInterceptor.java:333)
	... 14 more
log4j:WARN Continuable parsing error 3 and column 15
log4j:WARN Document root element "Configuration", must match DOCTYPE root "null".
log4j:WARN Continuable parsing error 3 and column 15
log4j:WARN Document is invalid: no grammar found.
log4j:ERROR DOM element is - not a <log4j:configuration> element.
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
09:03:14.418 [main] ERROR com.ethercis.vehr.VEhrGateServlet - ServiceManagerException errorCode=[resource.configuration.serviceFailed] location=[RunlevelManager.startupServices] message=[#1.0.0 Can't load plugin 'ResourceService']
09:03:14.418 [main] ERROR com.ethercis.vehr.VEhrGateServlet - Changing runlevel to 'RUNNING' failed, good bye
Exception in thread "Signal catcher thread for controlled shudown" java.lang.NullPointerException
	at com.ethercis.vehr.VEhrGateServlet.destroy(VEhrGateServlet.java:285)
	at com.ethercis.vehr.VEhrGateServlet.shutdownHook(VEhrGateServlet.java:435)
	at com.ethercis.servicemanager.cluster.SignalCatcher.run(SignalCatcher.java:216)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ethercis** [comment]
I have modified slightly your script (see below). Please also make sure you bind on a physical NIC not on the loopback.

#!/bin/bash
# description: Controls Ethercis Server
# processname: ecis-server
#
# SCRIPT created 15-10-2015, CCH
#-----------------------------------------------------------------------------------
UNAME=`uname`
HOSTNAME=`hostname`
export ECIS_DEPLOY_BASE=/opt/ecis
export SYSLIB=${ECIS_DEPLOY_BASE}/lib/system
export COMMONLIB=${ECIS_DEPLOY_BASE}/lib/common
export APPLIB=${ECIS_DEPLOY_BASE}/lib/application
export LIB=${ECIS_DEPLOY_BASE}/lib/deploy

# Mailer configuration
ECIS_MAILER=echo

# use the right jvm library depending on the OS
# NB: EtherCIS requires java 8
if [ :${UNAME}: = :Linux: ];
then
   JAVA_HOME=/opt/jdk1.8.0_74/jre
fi
if [ :${UNAME}: = :SunOS: ];
then
  JAVA_HOME=/jdk1.8.0_74/jre
fi

#force to use IPv4 so Jetty can bind to it instead of IPv6...
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

# runtime parameters
export JVM=${JAVA_HOME}/bin/java
export RUNTIME_HOME=/opt/ecis
export RUNTIME_ETC=/etc/opt/ecis
export RUNTIME_LOG=/var/opt/ecis
export RUNTIME_DIALECT=EHRSCAPE  #specifies the query dialect used in HTTP requests (REST)
export SERVER_PORT=8080 # the port address to bind to
export SERVER_HOST=192.168.2.115 # the network address to bind to

export MAILER_CONF=${RUNTIME_ETC}/xcmail.cf

export JOOQ_DIALECT=POSTGRES
JOOQ_DB_PORT=5432
JOOQ_DB_HOST=localhost
JOOQ_DB_SCHEMA=ethercis
export JOOQ_URL=jdbc:postgresql://${JOOQ_DB_HOST}:${JOOQ_DB_PORT}/${JOOQ_DB_SCHEMA}
export JOOQ_DB_LOGIN=postgres
export JOOQ_DB_PASSWORD=posgres

CLASSPATH=./:\
${JAVA_HOME}/lib:\
${LIB}/ecis-core-1.1.1-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-cache-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehrdao-1.1.0-SNAPSHOT.jar:\
${LIB}/jooq-pg-1.1.0-SNAPSHOT.jar:\
${LIB}/aql-processor-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-validation-1.0-SNAPSHOT.jar:\
${LIB}/ecis-transform-1.0-SNAPSHOT.jar:\
${LIB}/ecis-servicemanager-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-authenticate-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-logon-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-resource-access-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-composition-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-partyidentified-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-system-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-vehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-query-service-1.0.0-SNAPSHOT.jar:\
${APPLIB}/ehrxml.jar:\
${APPLIB}/oet-parser.jar:\
${APPLIB}/ecis-openehr.jar:\
${APPLIB}/types.jar:\
${APPLIB}/adl-parser-1.0.9.jar
# launch server
# ecis server is run as user ethercis
su - ethercis << _ECIS
case "$1" in
  start)
    echo "ethercis startup"
     ( ${ECIS_MAILER} ${MAILER_CONF} "EtherCIS Startup" "Manual invocation of server startup" > /dev/null )&
    (
	${JVM} \
	-Xmx256M \
	-Xms256M \
	-server \
	-XX:-EliminateLocks \
	-XX:-UseVMInterruptibleIO \
	-cp ${CLASSPATH} \
	-Xdebug \
	-Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y \
	-Djava.util.logging.config.file=${RUNTIME_ETC}/logging.properties \
	-Dlog4j.configuration=file:${RUNTIME_ETC}/log4j.xml \
	-Djava.net.preferIPv4Stack=true \
	-Djava.awt.headless=true \
	-Djdbc.drivers=org.postgresql.Driver \
    	-Dserver.node.name=vm01.ethercis.org \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=8999 \
    	-Dcom.sun.management.jmxremote.local.only=false \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
    	-Dfile.encoding=UTF-8 \
    	-Djava.rmi.server.hostname=${SERVER_HOST} \
	-Djooq.dialect=${JOOQ_DIALECT} \
	-Djooq.url=${JOOQ_URL} \
	-Djooq.login=${JOOQ_DB_LOGIN} \
	-Djooq.password=${JOOQ_DB_PASSWORD} \
	-Druntime.etc=${RUNTIME_ETC} \
	 com.ethercis.vehr.Launcher \
	-propertyFile /etc/opt/ecis/services.properties \
    	-server_host 192.168.2.115 \
    	-server_port 8080 \
 2>> ${RUNTIME_LOG}/ethercis_test.log >> ${RUNTIME_LOG}/ethercis_test.log &    )&
    ;;
  stop)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Stop" "Manual invocation of server STOP" > /dev/null )&
    echo "ethercis shutdown"
    pkill java
    ;;
  restart)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Restart" "Manual invocation of server RESTART" )&
    echo "ethercis restarting"
    $0 stop
    $0 start
    ;;
  clean)
    (${ECIS_MAILER} ${MAILER_CONF} "Ethercis CLEAR" "Manual invocation of server Clear logs" > dev/null )&
    echo "ethercis clear"
    $0 stop
	rm -rf {RUNTIME_LOG}/ethercis_test.log
    ;;
  *)
    echo "Usage: ecis-server {start|stop|restart|clean}"
    exit 1
esac
_ECIS
exit 0
# end of file

**Comment by ethercis** [comment]
I have modified your script slightly. Please also make sure you bind the server to a NIC IP address (do not use the loopback).

<pre><code>
#!/bin/bash
# description: Controls Ethercis Server
# processname: ecis-server
#
# SCRIPT created 15-10-2015, CCH
#-----------------------------------------------------------------------------------
UNAME=`uname`
HOSTNAME=`hostname`
export ECIS_DEPLOY_BASE=/opt/ecis
export SYSLIB=${ECIS_DEPLOY_BASE}/lib/system
export COMMONLIB=${ECIS_DEPLOY_BASE}/lib/common
export APPLIB=${ECIS_DEPLOY_BASE}/lib/application
export LIB=${ECIS_DEPLOY_BASE}/lib/deploy

# Mailer configuration
ECIS_MAILER=echo

# use the right jvm library depending on the OS
# NB: EtherCIS requires java 8
if [ :${UNAME}: = :Linux: ];
then
   JAVA_HOME=/opt/jdk1.8.0_74/jre
fi
if [ :${UNAME}: = :SunOS: ];
then
  JAVA_HOME=/jdk1.8.0_74/jre
fi

#force to use IPv4 so Jetty can bind to it instead of IPv6...
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

# runtime parameters
export JVM=${JAVA_HOME}/bin/java
export RUNTIME_HOME=/opt/ecis
export RUNTIME_ETC=/etc/opt/ecis
export RUNTIME_LOG=/var/opt/ecis
export RUNTIME_DIALECT=EHRSCAPE  #specifies the query dialect used in HTTP requests (REST)
export SERVER_PORT=8080 # the port address to bind to
export SERVER_HOST=192.168.2.115 # the network address to bind to

export MAILER_CONF=${RUNTIME_ETC}/xcmail.cf

export JOOQ_DIALECT=POSTGRES
JOOQ_DB_PORT=5432
JOOQ_DB_HOST=localhost
JOOQ_DB_SCHEMA=ethercis
export JOOQ_URL=jdbc:postgresql://${JOOQ_DB_HOST}:${JOOQ_DB_PORT}/${JOOQ_DB_SCHEMA}
export JOOQ_DB_LOGIN=postgres
export JOOQ_DB_PASSWORD=posgres

CLASSPATH=./:\
${JAVA_HOME}/lib:\
${LIB}/ecis-core-1.1.1-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-cache-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehrdao-1.1.0-SNAPSHOT.jar:\
${LIB}/jooq-pg-1.1.0-SNAPSHOT.jar:\
${LIB}/aql-processor-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-validation-1.0-SNAPSHOT.jar:\
${LIB}/ecis-transform-1.0-SNAPSHOT.jar:\
${LIB}/ecis-servicemanager-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-authenticate-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-knowledge-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-logon-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-resource-access-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-composition-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-partyidentified-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-system-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-ehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-vehr-service-1.1.0-SNAPSHOT.jar:\
${LIB}/ecis-query-service-1.0.0-SNAPSHOT.jar:\
${APPLIB}/ehrxml.jar:\
${APPLIB}/oet-parser.jar:\
${APPLIB}/ecis-openehr.jar:\
${APPLIB}/types.jar:\
${APPLIB}/adl-parser-1.0.9.jar
# launch server
# ecis server is run as user ethercis
su - ethercis << _ECIS
case "$1" in
  start)
    echo "ethercis startup"
     ( ${ECIS_MAILER} ${MAILER_CONF} "EtherCIS Startup" "Manual invocation of server startup" > /dev/null )&
    (
	${JVM} \
	-Xmx256M \
	-Xms256M \
	-server \
	-XX:-EliminateLocks \
	-XX:-UseVMInterruptibleIO \
	-cp ${CLASSPATH} \
	-Xdebug \
	-Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y \
	-Djava.util.logging.config.file=${RUNTIME_ETC}/logging.properties \
	-Dlog4j.configuration=file:${RUNTIME_ETC}/log4j.xml \
	-Djava.net.preferIPv4Stack=true \
	-Djava.awt.headless=true \
	-Djdbc.drivers=org.postgresql.Driver \
    	-Dserver.node.name=vm01.ethercis.org \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=8999 \
    	-Dcom.sun.management.jmxremote.local.only=false \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
    	-Dfile.encoding=UTF-8 \
    	-Djava.rmi.server.hostname=${SERVER_HOST} \
	-Djooq.dialect=${JOOQ_DIALECT} \
	-Djooq.url=${JOOQ_URL} \
	-Djooq.login=${JOOQ_DB_LOGIN} \
	-Djooq.password=${JOOQ_DB_PASSWORD} \
	-Druntime.etc=${RUNTIME_ETC} \
	 com.ethercis.vehr.Launcher \
	-propertyFile /etc/opt/ecis/services.properties \
    	-server_host 192.168.2.115 \
    	-server_port 8080 \
 2>> ${RUNTIME_LOG}/ethercis_test.log >> ${RUNTIME_LOG}/ethercis_test.log &    )&
    ;;
  stop)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Stop" "Manual invocation of server STOP" > /dev/null )&
    echo "ethercis shutdown"
    pkill java
    ;;
  restart)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Restart" "Manual invocation of server RESTART" )&
    echo "ethercis restarting"
    $0 stop
    $0 start
    ;;
  clean)
    (${ECIS_MAILER} ${MAILER_CONF} "Ethercis CLEAR" "Manual invocation of server Clear logs" > dev/null )&
    echo "ethercis clear"
    $0 stop
	rm -rf {RUNTIME_LOG}/ethercis_test.log
    ;;
  *)
    echo "Usage: ecis-server {start|stop|restart|clean}"
    exit 1
esac
_ECIS
exit 0
# end of file
</code></pre>

**Comment by maxcda101** [comment]
I'm ready binding the server to a NIC IP address, but new my stacktrace still the same.
I checked, then i finded file `/etc/opt/ecis/terminology.xml` did not exist, is it problem?

**Comment by ethercis** [comment]
I don't the missing terminology.xml is an issue, it is needed to populate the DB initially. 
Could you set your log level to debug to figure out where the issue is.
(your might want to check you don't have already a server instance running <code>ps -ef | grep java</code>)

**Comment by maxcda101** [comment]
I solved the problem, i edited line 39: export SERVER_HOST='MYHOSTNAME' and added 'MYHOSTNAME' to file hosts.
Thank you for your support.

**Comment by raphaeloneves** [comment]
Solved by removing the jar from the classpath and editing my ecis-server script. Thank you!

**Comment by Fedorov113** [comment]
I get the same issue and can't figure it out. How am I supposed to set up host on Ubuntu, for example? 
Thank you!
