### ISSUE TITLE
Setting 'is-persistent' flag in composition table

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#23]
Is this set internally from the composition archetype? If not how is this set? If this accessible via REST API?

**Comment by ethercis** [comment]
It is set to its default value 'true' since a composition is always persisted in EtherCIS.

**Comment by dileep-ehr** [comment]
The modelling tools allow defining the Compositions either as 'Event' or 'Persistent'. My understanding is that the Event compositions are event related and can occur multiple times in an EHR, whereas, Persistent compositions are summaries of health data (such as Family history) which occur only once per EHR (and gets updated periodically). Is this flag intended to support this kind of classification of compositions?

**Comment by freshehr** [comment]
Hi Dileep,

This is correct, IMO @ethercis - the is_persistent flag is, I think intended to be read-only and derived from the COMPOSITION/category value - which is mandatory and either 'event' or 'persistent' and will be pre-constrained via the underlying composition archetype. So I think you should probably just reflect that value read-only. It will virtually always be 'event'.

**Comment by dileep-ehr** [comment]
Hi Ian,
Thanks for the inputs. From Christian's input, I gather that while the field may be intended for what you mention, currently the functionality is not implemented. So it is being set to true by default for all the compositions, irrespective of what the COMPOSITION/category value, on the assumption that 'It will virtually always be 'event'. So it does not fulfill any logical purpose currently and can be assumed to be true always.

**Comment by freshehr** [comment]
Hi Dileep,

I agree, this is a bit academic, as AFAIK no current CDRs do anything with the Ispersistent flag or composition.category. One of the reasons is that there is recognition that the reality is a bit more subtle, and there is a CR for the RM to add other categories, so it is likely that the is_persistnet function will be dropped in future.

The requirement to adopt 'persistence' style commits i.e single instance updates is clear but I tend to just document this for developers, rather than use composition.category.

**Comment by dileep-ehr** [comment]
Dear Ian,

Thanks for the inputs. Taking cue from the dominant thought, we will also look at managing this outside the CDR for future compatibility. After all, as you mention, reality is not necessarily binary and can take many shades, which require the CDR to remain generic.
