### ISSUE TITLE
Add 'distinct' support to AQL

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#25]
Some population queries require 'distinct' results e.g.

`select
  distinct e/ehr_id/value as ehrId
  from EHR e
  contains COMPOSITION a
  contains EVALUATION a_a[openEHR-EHR-EVALUATION.adverse_reaction_risk.v1]
  where
    a/name/value='Adverse reaction list'
  and
   a_a/data[at0001]/items[at0002]/value/value like '%peanut%'`

Currently the distinct keyword creates an error

**Comment by ethercis** [comment]
I have posted a new version of the library on the test server. Please note this is a temporary fix since distinct can be fairly complex, but this one will work in 90% of the case IMO. In order to get it comprehensively fixed, the unioned queries must be dealt with as subqueries (e.g. select ... from (select ...) sub)). This is a significant change, but will allow support of statistical operators as well (min, max, avg etc.). Please leave this issue open, I will add this as an enhancement into the roadmap. Thanks
