### ISSUE TITLE
Failing tests in ecis-validation

### ISSUE THREAD

**Issue by ralphvanetten** [ethercis/ethercis#27]
I've spend a lot of time figuring out the root cause of the two failing tests but in the end I disabled them for now: https://github.com/ethercis/ehrservice/pull/5/commits/2be7834af55cadf9c64cc5ce8b98b4173916d2e7

After debugging I found that [`object'](https://github.com/ethercis/ehrservice/blob/remote-github/validation/src/main/java/com/ethercis/validation/wrappers/CDvCodedText.java#L52) never contains a derived class but only the baseclass. In this case the xml fragments mentions it is a `C_CODE_PHRASE` but the object is a `COBJECTImpl` and not a `CCODEPHRASEImpl` causing the validation to fail.

A screenshot of the variables when breaking on the `if instanceof` during the `testValidateElement` test.

![selection_300](https://user-images.githubusercontent.com/1533323/27780854-a1ff0a72-5fcb-11e7-925a-f95f4aa5927a.png)

I've tried many versions of the xmlbeans libraries but the issue remains. Is suspect either the test is wrong (perhaps that's why tests are disabled in the maven build?) or it depends on a really obscure version of some dependency.

**Comment by ethercis** [comment]
testCCDvCodedText() doesn't pass either. We don't have this problem in the running systems since we have disabled validating DvCodedText to remain compatible with Marand... 

Now what is missing in CDvCodedText::validate() is a changetype of the COBJECT similar to:

<pre><code>
Object object = csingleattribute.getChildrenArray(0);
object = ((COBJECT)object).changeType(CCODEPHRASE.type);
</code></pre>

Of course this should be done in a smart way, not brutally as above... nevertheless if the changetype is done, the validation works as expected.

**Comment by ralphvanetten** [comment]
A great, many thanks. So the test can safely be ignored for now.

**Comment by ethercis** [comment]
Yes, but if you feel in a mood to fix it, you're most welcomed!

**Comment by chevalleyc** [comment]
Fixed in v1.1.2
