### ISSUE TITLE
Rest api had been error 

### ISSUE THREAD

**Issue by maxcda101** [ethercis/ethercis#4]
Hi @ethercis 
I deployed service Ethercis on local, but i use Postgresql 9.5 then during the import process has generated error
```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 207; 3079 18552 EXTENSION jsquery 
pg_restore: [archiver (db)] could not execute query: ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/jsquery.control": No such file or directory
    Command was: CREATE EXTENSION IF NOT EXISTS jsquery WITH SCHEMA public;

pg_restore: [archiver (db)] Error from TOC entry 3429; 0 0 COMMENT EXTENSION jsquery 
pg_restore: [archiver (db)] could not execute query: ERROR:  extension "jsquery" does not exist
    Command was: COMMENT ON EXTENSION jsquery IS 'data type for jsonb inspection';
```
Is there any effect?

And when i test api but generated error 500

![api](https://cloud.githubusercontent.com/assets/11785724/25937943/d0eae452-3657-11e7-9f0e-5d0bce6190bf.png)

Also this api and data I posted on 178.62.71.220:8080 is successful
Hope you can help me, why do it.

Thanks.
Quan

**Comment by ethercis** [comment]
‎Hi,You need to compile and install the extension jsquery. This is required to deal with JSONB queries etc. I am not at my desk but if you google it you will find it. Cheers -- Christian                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Nguyen QuanSent: Thursday, 11 May 2017 14:43To: ethercis/ethercisReply To: ethercis/ethercisCc: Christian Chevalley; MentionSubject: [ethercis/ethercis] Rest api had been error (#4)Hi @ethercis
I deployed service Ethercis on local, but i use Postgresql 9.5 then during the import process has generated error
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 207; 3079 18552 EXTENSION jsquery 
pg_restore: [archiver (db)] could not execute query: ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/jsquery.control": No such file or directory
    Command was: CREATE EXTENSION IF NOT EXISTS jsquery WITH SCHEMA public;

pg_restore: [archiver (db)] Error from TOC entry 3429; 0 0 COMMENT EXTENSION jsquery 
pg_restore: [archiver (db)] could not execute query: ERROR:  extension "jsquery" does not exist
    Command was: COMMENT ON EXTENSION jsquery IS 'data type for jsonb inspection';

Is there any effect?
And when i test api but generated error 500

Also this api and data I posted on 178.62.71.220:8080 is successful
Hope you can help me, why do it.
Thanks.
Quan

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethercis/ethercis","title":"ethercis/ethercis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethercis/ethercis"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Rest api had been error  (#4)"}],"action":{"name":"View Issue","url":"https://github.com/ethercis/ethercis/issues/4"}}}

**Comment by maxcda101** [comment]
Thank you!
I installed the  extension jsquery, and import database ethercis not error. But these still exist api call error 500 :(

**Comment by ethercis** [comment]
You have to make sure the template related to your composition is present in /etc/opt/ecis/knowledge/operational_templatesYou can also upload it using a REST POST template (see REST API doc for this command)Cheers -- Christian                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Nguyen QuanSent: Thursday, 11 May 2017 18:03To: ethercis/ethercisReply To: ethercis/ethercisCc: Christian Chevalley; MentionSubject: Re: [ethercis/ethercis] Rest api had been error (#4)Thank you!
I installed the  extension jsquery, and import database ethercis not error. But these still exist api call error 500 :(

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethercis/ethercis","title":"ethercis/ethercis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethercis/ethercis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maxcda101 in #4: Thank you!\r\nI installed the  extension jsquery, and import database ethercis not error. But these still exist api call error 500 :(\r\n "}],"action":{"name":"View Issue","url":"https://github.com/ethercis/ethercis/issues/4#issuecomment-300756627"}}}

**Comment by maxcda101** [comment]
I added files into /etc/opt/ecis/knowledge/operational_templates, i'm missing because (https://github.com/ethercis/ethercis/blob/master/doc/vmized.md) dont talk to forder knowledge.
Then has generated error new.
```
HTTP ERROR: 500
Problem accessing /rest/v1/composition. Reason:
    #1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [insert into "ehr"."contribution" ("ehr_id", "contribution_type", "state", "system_id", "committer", "time_committed", "time_committed_tzid", "change_type", "sys_transaction") values (?, ?::"ehr"."contribution_data_type", ?::"ehr"."contribution_state", ?, ?, cast(? as timestamp), ?, ?::"ehr"."contribution_change_type", cast(? as timestamp)) returning "ehr"."contribution"."id"]; ERROR: value too long for type character varying(15)
```
Sorry to bother you.

**Comment by ethercis** [comment]
Not sure what's wrong here... I am out of the office until Tuesday next week. I will have a look next week. Thanks -- Christian                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Nguyen QuanSent: Thursday, 11 May 2017 18:59To: ethercis/ethercisReply To: ethercis/ethercisCc: Christian Chevalley; MentionSubject: Re: [ethercis/ethercis] Rest api had been error (#4)I added files into /etc/opt/ecis/knowledge/operational_templates, i'm missing because (https://github.com/ethercis/ethercis/blob/master/doc/vmized.md) dont talk to forder knowledge.
Then has generated error new.
HTTP ERROR: 500
Problem accessing /rest/v1/composition. Reason:
    #1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [insert into "ehr"."contribution" ("ehr_id", "contribution_type", "state", "system_id", "committer", "time_committed", "time_committed_tzid", "change_type", "sys_transaction") values (?, ?::"ehr"."contribution_data_type", ?::"ehr"."contribution_state", ?, ?, cast(? as timestamp), ?, ?::"ehr"."contribution_change_type", cast(? as timestamp)) returning "ehr"."contribution"."id"]; ERROR: value too long for type character varying(15)

Sorry to bother you.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethercis/ethercis","title":"ethercis/ethercis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethercis/ethercis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maxcda101 in #4: I added files into /etc/opt/ecis/knowledge/operational_templates, i'm missing because (https://github.com/ethercis/ethercis/blob/master/doc/vmized.md) dont talk to forder knowledge.\r\nThen has generated error new.\r\n```\r\nHTTP ERROR: 500\r\nProblem accessing /rest/v1/composition. Reason:\r\n    #1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [insert into \"ehr\".\"contribution\" (\"ehr_id\", \"contribution_type\", \"state\", \"system_id\", \"committer\", \"time_committed\", \"time_committed_tzid\", \"change_type\", \"sys_transaction\") values (?, ?::\"ehr\".\"contribution_data_type\", ?::\"ehr\".\"contribution_state\", ?, ?, cast(? as timestamp), ?, ?::\"ehr\".\"contribution_change_type\", cast(? as timestamp)) returning \"ehr\".\"contribution\".\"id\"]; ERROR: value too long for type character varying(15)\r\n```\r\nSorry to bother you."}],"action":{"name":"View Issue","url":"https://github.com/ethercis/ethercis/issues/4#issuecomment-300768067"}}}

**Comment by maxcda101** [comment]
i alter table ehr.contribution `time_committed_tzid: varchar(15) -> varchar(16)` Then no longer faulty. But i dont understand why so?

**Comment by freshehr** [comment]
Can you send over the value of the string that you committed to "time_committed_tzid"? It looks as if that was too long for the original character width of that column.

**Comment by freshehr** [comment]
As an example the test Ether Cis instance has 'Asia/Singapore' in that column.

**Comment by maxcda101** [comment]
@freshehr  Thank's
Value of the i committed to "time_committed_tzid" is "Asia/Ho_Chi_Minh". Long string is longer than 15 characters.
I think length of  "time_committed_tzid" defined long than 15 charactor.

**Comment by ethercis** [comment]
Many thanks for spotting out this issue!
There are other tables with this limit including:

- CONTRIBUTION_HISTORY
- EHR
- EVENT_CONTEXT
- EVENT_CONTEXT_HISTORY
- PARTICIPATION
- PARTICIPATION_HISTORY

As it seems, the timezone string could be as long as 38 chars. I suggest to alter the size to 40.
I will issue an SQL script and modify the DDL script accordingly.
Thanks again

**Comment by maxcda101** [comment]
I will wait for the new script and close this issue.
Best regards.
Quan from ThinkLabs-vn

**Comment by maxcda101** [comment]
> As it seems, the timezone string could be as long as 38 chars. I suggest to alter the size to 40.
I will issue an SQL script and modify the DDL script accordingly.

@ghost @chevalleyc 

AFAIK, you still do not update both of the SQL script and DDL script.
Do you have any ETA for this update?

Thanks  
Quan from ThinkLabs-vn

**Comment by chevalleyc** [comment]
Updated DDL are now located in https://github.com/ethercis/ehrservice/tree/remote-github/db (timezone id is now TEXT)
Please use these instead of what is posted in the doc. Thanks

**Comment by maxcda101** [comment]
I have just seen the DDL file which is changed and I don't know how to migrate my database. Furthermore, I don't know how to use https://github.com/ethercis/ehrservice/tree/remote-github/db. Can you tell me how to migrate the database and use it?
Thanks

**Comment by chevalleyc** [comment]
The simplest way is to manually alter the DB on the xyz_tzid field. You can use PgAdmin or another SQL enable DB client (DataGrip, WebMin etc.). The query is something like:

```ALTER TABLE ehr.event_context ALTER COLUMN start_time_tzid TYPE text;

For all column you need to modify.

NB. Make sure you backup your DB before doing the change (https://github.com/ethercis/ethercis/blob/master/doc/DB%20administration.md)
