### ISSUE TITLE
Merging of duplicate EHRs for the same person

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#51]
There is a chance of the same person getting more than one EHR ID, either because of the limitations of the demographic server in identifying duplicates or when integrating EHR data for a person from multiple systems.

Is Ethercis planning to allow merging of duplicate EHRs for the same person? Can this be added to the roadmap?

**Comment by chevalleyc** [comment]
There should be only one EHR per person. The issue comes from allowing multiple identities for the same person (multiple spelling for the same name f.e.). This is normally solved using a master patient index. 
In your scenario, the merge can be done "behind the scene" by re-referencing ehr_id in tables that reference it as a foreign key: status, contribution, composition. 
IMO, this is more a database maintenance procedure than an EtherCIS function.

**Comment by dileep-ehr** [comment]
Thanks Christian,

I realize that this is not strictly an EHR functionality. I was just
curious to know if there was any ready APIs to do this in Ethercis.

Regards

Dileep V S
*Founder*
HealtheLife Ventures LLP
m: +91 9632888113
a: 103, Innovation Centre, IIIT, Electronics City, Bangalore 560100
w: healthelife.in  e: dileep@healthelife.in

**Comment by tony-shannon** [comment]
closing this @dileep-ehr on advice from @chevalleyc  , please reopen if any related issues
