### ISSUE TITLE
EtherCIS build

### ISSUE THREAD

**Issue by rubal-jain** [ethercis/ethercis#56]
Hi Team,
We have been successfully able to build and run the ethercis project in our local system using maven. We encountered a lot of roadblocks in the way and have documented each and every process. A brief about the process:
1. The repository eCIS-LIB is not available in the github and we had to manually install each and every jar.
2. service.properties and log4j2 was missing from resouces directory
3. DataAccessException needed to be removed from ResourceService.java
4. Versions for some of the jars had to be updated
5. antlr4 was missing
6. Output directory in aql-processor pom file changed to "/target/generated-sources/antlr4/com/ethercis/aql/parser"
7. Added dependency :
       <dependency>
            <groupId>ethercis</groupId>
            <artifactId>ecis-resource-access-service</artifactId>
            <version>1.1.0-SNAPSHOT</version>
        </dependency>
in vEhr launcher module
8. Added REST configuration in service.properties :
//REST Configuration
server.mode.dialect=EHRSCAPE
server.mode.dialect.root=/rest/v1
server.service.class.def=com.ethercis,com.colnec
9. Change session.timeout=86400000 in services.properties

After all this, we have been successfully able to run ethercis on our machines. We have some doubts however, about this configuration. We had forked the 3 projects to our private github network. This was done 15 days ago. After that the projects have undergone some changes. Will we have to fork it again?
Also, when we forked the project, the config folder in jooq-pg was not available. Will I have to clone the project and build it again?

Our plan is to successfully run ethercis and fix bugs as we encounter them. As of now, we have a few open bugs which my colleague has already raised in github. We plan on resolving those bugs. If it is possible, you can take a pull from us and publish it if it is suitable. 
 
Let me know your thoughts on all of this.

Thanks a ton,
Rubal Jain

**Comment by tony-shannon** [comment]
many thanks @rubal-jain 

Appreciate that update.
Our documentation on the build process looks likes it needs some improvement then, I wonder if your notes could be used to offer some improvements?
http://docs.ethercis.org/building.html

Christian @chevalleyc  is busy juggling a variety of project related issues now, so am trying to guard his time. 

As to your forks & changes.. glad to hear you are leveraging this tool.  
It's always best to communicate ahead of time on a project like this..  as you'll understand we are trying to improve the tool all the time.. ie see our latest project/product roadmap here.
https://github.com/ethercis/ethercis/blob/master/ethercis-roadmap.md
If your trying to keep aligned then best to communicate your plans up front here, rather than after the event..

Should also mention, as we are now starting to scale up  we're having to draw folks attention to the level of support we can offer for this sophisticated software ..  please see here;
https://github.com/ethercis/ethercis#productproject-support

The work you've done sounds useful and valuable and we would be interested in a pull request, but need to get a view from @chevalleyc  as to when he may have the time to review.

Hope you will appreciate and understand that we need to make this effort sustainable for all of us, (i.e. otherwise its not sustainable :o)

thanks
Tony

**Comment by tony-shannon** [comment]
As there has been no update on this, will close this issue for now
