### ISSUE TITLE
Template(opt) is missing after restarting ethercis 

### ISSUE THREAD

**Issue by linto17** [ethercis/ethercis#76]
Hi, operational templates are missing after ethercis restart

Thanks,
Linto

**Comment by tony-shannon** [comment]
No enough information in this issue is first impression.

Please provide a good deal more if you want to discuss..

**Comment by linto17** [comment]
Template is not listed in get-templates(/rest/v1/template).

**Comment by tony-shannon** [comment]
what Template? Any template..?

**Comment by linto17** [comment]
No, I have attached the templates which are missing after ethercis restart.
[opt.zip](https://github.com/ethercis/ethercis/files/1483041/opt.zip)

**Comment by tony-shannon** [comment]
Thanks, I still dont understand your issue , but Christian will take a look when he gets a chance
thanks
Tony

**Comment by chevalleyc** [comment]
Please could you come with a systematic description of this issue. We use this feature a lot and never experience any problem so far. Please note your template might be corrupt whenever input (Windows CR/LF is a common problem).

**Comment by linto17** [comment]
Thanks, I used windows to create templates. Do you have any idea to check the template is corrupt or how to replace the CR/LF?

**Comment by dileep-ehr** [comment]
The problem is that the indexes for some of the templates seem to get deleted from Ethercis data base after a restart and so queries and  commits for them stop working. They are also not listed in get-templates, but continue to be available in the /etc/opt/ecis/knowledge/operational_templates folder. If we submit the opts again, they get listed in get-templates and queries & commit start working .

We are using Archetype editor & Template designer to create opts and so Windows CR/LF could be a culprit. We have also observed that this happens specifically with some opts(attached earlier by Linto) and not others. We will investigate and see if we can fix the Windows CR/LF.

Also in Episode and wellness service, we have used some custom archetypes, which again may carry the Windows CR/LF errors.

**Comment by chevalleyc** [comment]
You should have a look to the server log, it will tell you how many templates are loaded and how many in errors, and also errors parsing templates. For templates in error, you can convert them from a linux shell and run command dos2unix (you may have to install it). Templates in error are generally badly terminated (that is a </template> followed by garbage).

**Comment by shafeef** [comment]
Thanks, I converted those templates using dos2unix. but still it's giving same error.
here i had attached the error logs:-

ERROR com.ethercis.ehr.knowledge.KnowledgeCache - Could not parse operational template:EHRN Episode details.v0 error:org.apache.xmlbeans.XmlException: error: Unexpected element: CDATA

ERROR com.ethercis.ehr.knowledge.KnowledgeCache - Could not parse operational template:EHRN Wellness service.v0 error:org.apache.xmlbeans.XmlException: error: Unexpected element: CDATA

ERROR com.ethercis.ehr.knowledge.KnowledgeCache - Could not parse operational template:EHRN Problem list.v0 error:org.apache.xmlbeans.XmlException: error: Unexpected element: CDATA

**Comment by chevalleyc** [comment]
Yes that's exactly what I meant: your template contains unrecognized character(s). Check also if you have some unexpected leading character(s).

**Comment by linto17** [comment]
@shafeef @chevalleyc It happening because we used to inject the same opt again and again then existing opt get conflicts.
