### ISSUE TITLE
Azure Install does not complete

### ISSUE THREAD

**Issue by johnmeredith** [ethercis/ethercis#8]
I have successfully created a docket container on Azure and can run the install fine but it does not seem to complete. However it fails when launching the app, the terminal seems to hang. 

[azure_install log.txt](https://github.com/ethercis/ethercis/files/1091422/azure_install.log.txt)

**Comment by ethercis** [comment]
I John, I saw in the openEHR news that it was actually deployed now. Could you please confirm? Thanks

**Comment by johnmeredith** [comment]
The problem is that it is flaky and even when it can be successfully installed – the ports themselves do not expose correctly in an Azure Container Service. I have not yet tried running a different sort of Azure VM though. The app forwards 8080->8888 which needs to be exposed in ACS but the Docker container has problems with this and doesn’t seem to be listening on that port. I logged into app container itself and we pinged the IP it was running on (10.0.0.5). It is running but not working…

**Comment by ethercis** [comment]
Ok I get it. I think what needs to be done is a better logging to help diagnose issue like this one. I think nevertheless that since the listener binding requires to resolve the hostname to bind to (see [InetSocketAddress](https://docs.oracle.com/javase/7/docs/api/java/net/InetSocketAddress.html)). The simplest configuration (/etc/hosts) should resolve hostname to an actual NIC or any public IP address for your container. See ethercis lauch script (ecis-server), parameters server_host and server_port that might need to be tweaked...

**Comment by chevalleyc** [comment]
Now addressed as how to install EtherCIS on Windows. Will publish a doc summarizing this when done. Thanks
