### ISSUE TITLE
EtherCIS demo envir needs reboot, can we trigger alert ?

### ISSUE THREAD

**Issue by tony-shannon** [ethercis/ethercis#94]
Hi @chevalleyc 
demo instance of EtherCIS froze mid meeting today.. is there a way to trigger alert re pending crash/need to reboot? eg to email 
thanks
T

**Comment by chevalleyc** [comment]
# process monitoring
Process monitoring is dependent on the deployment architecture. There is no quick answer to your question. The demo instance is what it is: a demo. I am not sure the effort of installing/configuring a process monitoring (or writing script to do it) is time well invested, since a very different approach will be used in a near future whenever ethercis service instance cluster will be used (this will provide fault recovery etc.)

# This is a "postmortem" analysis of this event. I keep this as reference for future production deployment

NB. No java coredump found. 
NB2. Tons of attacks from 61.177.172.189 (CHINANET-JS) also from UNICOM-HE, UNICOM-HN, DHCP-FTTB-CHT-46-118-40-GTUA (Ukraine), BORANET etc... EtherCIS should not be exposed to the net.

Going through the log shows that the max sessions for user 'guest' has been exhausted (20 sessions). This issue on setting up more sessions from the **client** side has been discussed at length and documented. EtherCIS behavior was normal in this context. Sessions exhaustion occured at 11:29 GMT. 

Following this event, at 11:31:40, postgres invoked an OOM killer (free some unnecessary processes due to Out of Memory). At the same time kernel killed the java process (EtherCIS) due to memory exhaustion.

```
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [ 4820]  1001  4820   618949   123534     337        0             0 java
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [ 4851]    26  4851    92774    10351      83        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [10383]    26 10383    94097    11609      86        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [10384]    26 10384    95473    13018      89        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [12815]    26 12815    92580     9900      83        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [12816]    26 12816    92144     9611      82        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [12817]    26 12817    93637    11405      83        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [10117]  1001 10117    48067      589      19        0             0 xfsallocd
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [21628]    26 21628    89987     7010      78        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [21909]    26 21909    89609     6505      76        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [29694]     0 29694    33928      308      70        0             0 sshd
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [29696]  1000 29696    33928      309      66        0             0 sshd
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [29697]  1000 29697    13164      141      29        0             0 sftp-server
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [32525]    89 32525    22797      250      44        0             0 pickup
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [  417]     0   417    28095     8129      57        0             0 /usr/libexec/we
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [  441]     0   441     2901       51      11        0             0 sh
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [  443]     0   443   207047     8074     149        0             0 yum
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: [  463]    26   463    84441      555      50        0             0 postgres
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: Out of memory: Kill process 4820 (java) score 487 or sacrifice child
Jan  9 11:31:40 ethercis-test-aql-ldn kernel: Killed process 4820 (java) total-vm:2475796kB, anon-rss:494136kB, file-rss:0kB
```
CPU usage is very high:

```
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
7535 ethercis  20   0  192268   4592    976 S 49.8  0.5 170:10.92 xfsallocd
 4421 ethercis  20   0  192268   4120    976 S 49.5  0.4 236:50.75 xfsallocd
```
Seems XFS is busy with a segfault (recurring). checking out if a server reboot fix this issue (no server restart since 6 months).
Following the system reboot, xfsallocd issue seem to have disappeared.

**Comment by tony-shannon** [comment]
ok thanks @chevalleyc 

Can you outline your thinking re the forthcoming "ethercis service instance cluster will be used (this will provide fault recovery etc" you mention?  More info on that would be appreciated

Let me get view from @robtweed as to whether his qewd microservices approach could help with protection here?

**Comment by chevalleyc** [comment]
I'm happy to discuss various system design/infrastructure and deployment strategies/budget in a separate thread. I don't think this specific issue is at all related to EtherCIS GITHUB code base and should therefore be closed. Thanks.

**Comment by tony-shannon** [comment]
ok thanks @chevalleyc 
Will close for now, thanks
